/** Declaration file generated by dts-gen */

export = paga_business;

declare function paga_business(build: any): any;

declare namespace paga_business {
    function Builder(): any;

}



